//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizer
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Controls;

    public partial class Article
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }

        public RecordWindow GetEditWindow()
        {
            RecordWindow window = new RecordWindow();
            Control control = GetEditControl();
            Grid.SetRow(control, 0);
            window.Win.Children.Add(control);
            window.Title = FullName;
            window.Height = WindowHeight;
            return window;
        }

        public virtual Control GetEditControl()
        {
            throw new ArithmeticException();
        }

        public virtual decimal Money{get;}
        public virtual string FullName { get; }
        public virtual int WindowHeight { get; }
    }
}
