//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizer
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Controls;
    
    public partial class Birthday : Event
    {
        public int NextBirthdayId { get; set; }
        public string Relation { get; set; }
        public System.DateTime DateOfBirth { get; set; }
    
        public virtual Schedule NextBirthday { get; set; }

        public override string EventTypeRus
        {
            get { return "День рождения"; }
        }

        public override string EventType
        {
            get { return "Birthday"; }
        }

        public override int EditControlHeight
        {
            get { return 250; }
        }

        public override int ShowControlHeight
        {
            get { return 320; }
        }

        public override void Initialize(DateTime date)
        {
            Priority = 1;
            DateOfBirth = (DateTime)date;
            Repeat = "Ежегодно";
        }

        public override Control GetEditControl()
        {
            BirthdayEditControl control = new BirthdayEditControl();
            control.DataContext = this;
            return control;
        }

        public override Control GetShowControl()
        {
            BirthdayShowControl control = new BirthdayShowControl();
            control.DataContext = this;
            return control;
        }
    }
}
