//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Birthday : Event
    {
        public System.DateTime DateOfBirth { get; set; }

        public override DateTime TimeStamp
        {
            //Возвращает ближайший день рождения
            get
            {
                DateTime timestamp = new DateTime(DateTime.Now.Year, DateOfBirth.Month, DateOfBirth.Day);
                if (DateTime.Today > timestamp)
                    timestamp = timestamp.AddYears(1);

                return timestamp;
            }
        }
    }
}
