//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizer
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Controls;

    public partial class Expenditure : Article
    {
        public int TypeId { get; set; }
        public int NameId { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Summ { get; set; }
    
        public virtual ExpenditureName ExpenditureName { get; set; }
        public virtual ExpenditureType ExpenditureType { get; set; }
        

        public override Control GetEditControl()
        {
            ExpenditureEditControl edit = new ExpenditureEditControl();
            edit.DataContext = this;
            return edit;
        }

        public override decimal Money
        {
            get { return (decimal)Summ; }
        }

        public override int WindowHeight { get { return 380; } }

        public override string FullName
        {
            get
            {
                if (Id > 0)
                {
                    using (organizerEntities db = new organizerEntities())
                    {
                        if(db.Entry(this).State==System.Data.Entity.EntityState.Detached)
                            db.Article.Attach(this);

                        if (!db.Entry(this).Reference(e => e.ExpenditureType).IsLoaded)
                            db.Entry(this).Reference(e => e.ExpenditureType).Load();

                        if (!db.Entry(this).Reference(e => e.ExpenditureName).IsLoaded)
                            db.Entry(this).Reference(e => e.ExpenditureName).Load();
                    }

                    return $"{ExpenditureType.Type}: {ExpenditureName.Name}";
                }
                else
                    return "New Record";
            }
        }
    }
}
