//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizer
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Controls;

    public partial class Expenditure : Article
    {
        public int TypeId { get; set; }
        public int NameId { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Summ { get; set; }
    
        public virtual ExpenditureName ExpenditureName { get; set; }
        public virtual ExpenditureType ExpenditureType { get; set; }
    }
}
