//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday : Event
    {
        public int HolidayDateId { get; set; }
        public bool Bank { get; set; }
    
        public virtual Schedule Date { get; set; }
    }
}
