//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizer
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Controls;

    public partial class Income : Article
    {
        public int SourceId { get; set; }
        public decimal Summ { get; set; }
    
        public virtual IncomeSource IncomeSource { get; set; }
    }
}
