//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organizer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepeatedEvent : Event
    {
        public int PrimeEventId { get; set; }
        public int ScheduleId { get; set; }
    
        public virtual Event MainEvent { get; set; }
        public virtual Schedule RepeatTime { get; set; }
    }
}
